<?php
class Main {

	public function run() {
		//echo "Hi there, its just a check";
		ob_start(); // output buffering function. To output dynamic functions as normal strings.
		require_once(URL::getPage());
		ob_get_flush(); // to return the value generated by the code as a normal string.
	}

}